packages:
  - packages/*
  - docs
catalog:
  nuxt-auth-utils: ^0.5.10
  tsx: ^4.19.2
  typescript: 5.6.3 # https://github.com/nuxt/module-builder/issues/141
  unbuild: ^3.3.1
  vitest: ^3.0.4
  better-auth: ^1.1.15
  '@nimiq/core': ^2.0.6
  defu: ^6.1.4
  nuxt: ^3.15.4
